### PR TITLE
Feature - Add linting

### LINKED ISSUE #99: Repo setup for developer experience DX
It's almost straightforward to start contributing to the repo. I like to improve the DX for future contributors:

### Update Node engine to v14 LTS

Most devs use v14 LTS, but the `develop` branch is strictly requiring v12 of the engine.

### `.editorconfig`

Unifies the codebase styling

```
root = true

[*]
indent_style = space
indent_size = 2
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = false
```

### `.prettierrc`

Works along with `.editorconfig`
```
{
  "arrowParens": "avoid",
  "semi": false,
  "useTabs": false,
  "tabWidth": 2,
  "singleQuote": true,
  "printWidth": 120,
  "trailingComma": "es5"
}
```

### Scripts in `package.json`

For linting and formatting the code if the IDE can't pick up Prettier

```json
"scripts": {
    "format": "prettier --write \"**/*.{js,jsx,ts,tsx,json,md}\"",
    "lint": "eslint src/ --ext .js,.ts,.tsx",
}
```

### PR DESCRIPTION
**Pull request by adamazad**
### Summary

- Adds ESLint.
- Adds Prettier for code formatting.
- Adds GitHub action to trigger linting on PRs, and pushes to any branch.
- Closes #99

### CODE REVIEW

**Comment by AugustoL** [comment]
@adamazad change the node version in the github workflows too please.

**Comment by AugustoL** [comment]
@adamazad seems that the build command is failing, can you check if you can run `yarn build` with this changes?

**Comment by adamazad** [comment]
> @adamazad seems that the build command is failing, can you check if you can run `yarn build` with this changes?

Here's the issue:

```bash
Failed to compile.

src\stores\ConfigStore.ts
  Line 10:1:  Import in body of module; reorder to top  import/first
  Line 11:1:  Import in body of module; reorder to top  import/first

Search for the keywords to learn more about each error.
```
https://github.com/AugustoL/dxvote/blob/d2b26001824dd4c5241546921d60fee300484ff9/src/stores/ConfigStore.ts#L1-L12

**Comment by adamazad** [comment]
@AugustoL, builds succeed locally.

**Comment by AugustoL** [comment]
Last change can you set the CI to false in the github workflows for it to succedd?
```
8:10:02 PM: Treating warnings as errors because process.env.CI = true.
8:10:02 PM: Most CI servers set it automatically.
8:10:02 PM: 
8:10:02 PM: Failed to compile.
```
https://app.netlify.com/sites/dxvote-dev/deploys/61369ecb3e9cfa00077fbc64#L100

**Comment by adamazad** [comment]
> Last change can you set the CI to false in the github workflows for it to succedd?
> 
> ```
> 8:10:02 PM: Treating warnings as errors because process.env.CI = true.
> 8:10:02 PM: Most CI servers set it automatically.
> 8:10:02 PM: 
> 8:10:02 PM: Failed to compile.
> ```
> 
> https://app.netlify.com/sites/dxvote-dev/deploys/61369ecb3e9cfa00077fbc64#L100

That's controlled in Netlify. You should be able to [set `CI=false`](https://stackoverflow.com/a/62490508/2151050)

**Comment by adamazad** [comment]
@AugustoL, merge when you think appropriate, please.

**Pull request merged**
