### PR TITLE
Feature/guilds landing skeleton

### PR DESCRIPTION
**Pull request by carlbarrdahl**
# Description

Add loading skeleton to GuildsPage

Closes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

# Checklist:

- [ ] My code follows the existing style of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any UI changes have been tested and made responsive for mobile views

### CODE REVIEW

**Comment by rossneilson** [comment]
We should add a check for empty and error to not just infinitely show loading

**Review by hhamud — DISMISSED** [review]

**Review by rossneilson — CHANGES_REQUESTED** [review]
We should add a check for empty and error to not just infinitely show loading

**Comment by carlbarrdahl** [comment]
> We should add a check for empty and error to not just infinitely show loading

Where can I find the designs for the emprt and error states?

**Comment by rossneilson** [comment]
> > We should add a check for empty and error to not just infinitely show loading
> 
> Where can I find the designs for the emprt and error states?

Just a blank screen, no cards displayed will do for now

**Review by rossneilson — APPROVED** [review]

**Pull request merged**
