### PR TITLE
warning of Dev Mode

### PR DESCRIPTION
**Pull request by luchux**
A way to show that we are not in production.

Screen Shot 2021-11-08 at 9 42 53 AM

### CODE REVIEW

**Comment by rossneilson** [comment]
I think the idea is more to show this message on any URL that is not dxvote.eth
So as a test, this message should appear on the ipfs deployment previews and only not show up on dxvote.eth.link | dxvote.eth.limo

Since we have a lot of QA testing environments that use the same environment config we need to show this there since anyone can access it.

Also I wonder if once it shows on those sites then maybe "Testing Environment" would be a better message

**Comment by luchux** [comment]
@rossneilson changed it! checking for the domain safely with windows  (react-router dom useLocation is domain agnostic).

**Comment by rossneilson** [comment]
> @rossneilson changed it! checking for the domain safely with windows (react-router dom useLocation is domain agnostic).

Awesome, we could even change it to just check for 'dxvote.eth'

**Comment by luchux** [comment]
@rossneilson ok, np updated it.

**Review by rossneilson — APPROVED** [review]

**Pull request merged**
