### PR TITLE
Feature/172 refactor inline styles

### PR DESCRIPTION
**Pull request by luchux**
Done: 
- refactored reusable components in common module: Box, Title, Subtitle, Row. 
- refactored page components of /proposals, /proposal, /info, /user, /config to use previous refactored components.
- removed as much as possible inline styles (limited re-markup in the refactor, mainly styled components in those pages)
- refactored modal wallet connected, to align button with wallet address and remove unnecessary inline styles.
- refactored governance table styles, instead of markup with fixed width, using table with css grid (browser support: https://caniuse.com/mdn-css_properties_display_grid) 
- fixed typo in  README.md about cache file. 
- Refactored tables of Schemas, Financial, and Governance info: introduced common components Table, TableHeader, HeaderCell, TableBody, TableRow, CellData to keep semantic consistency of tables (potentially usage of divs, for now html5 semantics of table elements). 

e
Screen Shot 2021-09-29 at 7 00 47 PM
screencapture-localhost-3000-2021-09-29-18_59_45

Screen Shot 2021-09-28 at 9 55 41 PM

WIP: 
- there are still many style={{}} in components that shouldn't do have it following the style guides. 
- there are potential reusable components to abstract from repetition of code.

### CODE REVIEW

**Review by hhamud — APPROVED** [review]
Great Job with the refactoring!

**Comment by AugustoL** [comment]
I added comments in the #203 and you have commits from that PR here too, same comments from that PR here then. Which one should we merge first?

**Comment by luchux** [comment]
@AugustoL @rossneilson resolved conflicts, and merged the other branches in this PR so we only have one.

**Comment by AugustoL** [comment]
@luchux the permissions table still has the old format.

**Comment by luchux** [comment]
@AugustoL you are right! sorry, confused permissions with proposals haha. Will add that one and fix new conflicts. 
ate ja!

**Comment by luchux** [comment]
@AugustoL a ver ga - briel!

**Pull request merged**
