### PR TITLE
Improve proposal search

### LINKED ISSUE #228: Improve Proposals Search
Proposals search in DXvote right now is case sensitive, which leads to bad UX. We should make it case-insensitive. We can possibly even look at improving search results by using fuzzy search. (We can use a lightweight library like FlexSearch / Fuse.js for this.)

### PR DESCRIPTION
**Pull request by mprasanjith**
This PR updates the proposal search implementation to support fuzzy search using [MiniSearch](https://github.com/lucaong/minisearch), and is much more performant and accurate now. The library is quite lightweight so I believe it shouldn't affect the bundle size too much. 

The code for handling search and filtering in the proposals component has been refactored as well to be more readable.

Fixes #228.

### CODE REVIEW

**Comment by luchux** [comment]
@AugustoL @rossneilson given that this will conflict with my PR on prposals order, do you think is better if I merge this PR with mine, and fix conflict and then we merge that with develop? 
anyways, whatever the order, ping me to fix the conflicts because this two PRs touches similar parts.

**Review by AugustoL — APPROVED** [review]
@luchux lets merge this one first, and then you can sync with mainnet

**Comment by luchux** [comment]
@AugustoL sweet. will keep an eye on develop to see when is merged and pull on my branch and fix from there ;)
cheers.

**Comment by mprasanjith** [comment]
@luchux Sorry to keep you waiting. Merged.

**Pull request merged**
