### PR TITLE
Feature/guilds landing

### PR DESCRIPTION
**Pull request by 0xvangrim**
# Description

New PR:
- Added `GuildRegistry` to the `hardhat.config`
- Checked in an updated version of `yarn.lock`
- Fixed broken test

Old PR below:
# Description
[Guilds landing Page](https://github.com/DXgovernance/dxvote/issues/678)
Screenshot 2022-03-20 at 22 24 06

The first implementation of the Guilds Landing Page together with the new SC `GuildRegistry`. Except for the design, these are the following features enabled:

- Dynamic guilds amount that fetches data from the SC
- Dynamic names (ENS)
- Dynamic subdomains (ENS)

TODO (Not sure if any of the below can be down as of now?)
- Add dynamic member count
- Add dynamic proposal count
- Add dynamic logo

The subdomain name is simply pushed to the back looking like `guilds/rinkeby/[RANDOM_GUILD]`. I am aware that we are going to change it later to be a proper subdomain. Should be an easy fix when we've deployed the new ENS name though.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ X ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [X ] My code follows the existing style of this project
- [X ] I have performed a self-review of my own code
- [X ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ X ] Any UI changes have been tested and made responsive for mobile views

### CODE REVIEW

**Review by hhamud — COMMENTED** [review]
The guilds name is missing from the guilds card when I use it. 
image

I also get an undefined in the url when I click on the guild card. 
image

**Comment by 0xvangrim** [comment]
> The guilds name is missing from the guilds card when I use it. image
> 
> I also get an undefined in the url when I click on the guild card. image

Yeah, that is to be expected. We haven't added our guild there yet since I am not the owner of our guild's smart contract. So, for now, it is only for display purposes.

**Comment by hhamud** [comment]
> > The guilds name is missing from the guilds card when I use it. image
> > I also get an undefined in the url when I click on the guild card. image
> 
> Yeah, that is to be expected. We haven't added our guild there yet since I am not the owner of our guild's smart contract. So, for now, it is only for display purposes.

That makes sense. Is there not a clearer view when there are no guilds available that the user is not a part of?. e.g. something like no guilds available at all on the landing page before clicking on the guilds card.

**Comment by 0xvangrim** [comment]
> > > The guilds name is missing from the guilds card when I use it. image
> > > I also get an undefined in the url when I click on the guild card. image
> > 
> > 
> > Yeah, that is to be expected. We haven't added our guild there yet since I am not the owner of our guild's smart contract. So, for now, it is only for display purposes.
> 
> That makes sense. Is there not a clearer view when there are no guilds available that the user is not a part of?. e.g. something like no guilds available at all on the landing page before clicking on the guilds card.

I think that's a good idea, but we do not have some functionality yet so I think it is better to see this as a first implementation and improve upon it later on. What do you think?

**Comment by 0xvangrim** [comment]
@hhamud the latest commits will make it possible to click on the `Guild` now.

**Review by hhamud — APPROVED** [review]

**Pull request merged**
