### PR TITLE
Rename xdai chain to gnosis chain

### LINKED ISSUE #533: Rename xdai to Gnosis chain
With Gnosis' acquisition of xdai and subsequent renaming to gnosis chain we need to update our app to reflect this.
Chain ID stays the same, just display name changes. 

Going off of official docs, it looks like icon is the same for now
https://www.xdaichain.com/

### PR DESCRIPTION
**Pull request by MiltonTulli**
### Summary
Rename xDai chain to Gnosis chain

### Issue(s)
https://github.com/DXgovernance/dxvote/issues/533

### CODE REVIEW

**Review by rossneilson — DISMISSED** [review]
Looks great, lets leave this out of develop until we decide to change the name as a DAO 👍

**Comment by rossneilson** [comment]
We got new logos for gnosis chain, they are in the design channel, would be good to update the PR with them

**Comment by rossneilson** [comment]
Hey, this has some conflicts ;)

**Review by rossneilson — APPROVED** [review]

**Comment by MiltonTulli** [comment]
@rossneilson  Are we waiting for dao's confirmation to merge or is good to go?

**Comment by rossneilson** [comment]
> @rossneilson Are we waiting for dao's confirmation to merge or is good to go?

nah, lets do it

**Pull request merged**
