### PR TITLE
Feature/172 refactor proposals

### PR DESCRIPTION
**Pull request by luchux**
This is a continuation of the work created in PR 200,  https://github.com/DXgovernance/dxvote/pull/200
The reason for this new PR in a different branch is because this PR focuses only on proposals page (recent work changed by Rossneilson). 

Done: 
- refactored all the tables to use grid css in reusable components in Table module. Columns take a width in a grid, and we can set up any layout for responsiveness (right now only each columwn percentage, but we can set up in the future easily a minmax for each column). 
- Refactored the Left Sidebar and Main content Layout to use also grid css (no more fixed width, just percentages 20% 80%, for example to the grid). This makes the layout responsive. 

Screen Shot 2021-09-30 at 8 46 48 PM

### CODE REVIEW

**Comment by AugustoL** [comment]
image
Last column in the propopsals table should be a bit bigger!

**Comment by AugustoL** [comment]
The table is the PermissionsInformation component is not refactored, maybe this is why im not seeing it in the deployment. Thats missing as well.

**Comment by AugustoL** [comment]
I have to say, it is a big refactor but much needed and it looks good. Lets try to get this merge soon to avoid future conflicts.

ping @rossneilson for a quick review too, but I think I caught up all "issues"

Great work @luchux !

**Comment by luchux** [comment]
@AugustoL fixed papi, increased the columns a bit so they don't brake with the possibles scenarios. Given the new layout (sidebar at the left, needed to decrease 1px the proposal Title as well). ate ja! 
Screen Shot 2021-10-01 at 7 58 07 AM

**Comment by rossneilson** [comment]
Great refactor @luchux !
I'll mostly echo what Augusto said in regards to duplicated changes in 2 PRs, best to choose one to merge first.
Also would be good to have the buttons in the sidebar be a consistent size, seems they are different currently, maybe best to fix merge conflicts first.

**Pull request closed without merging**
